services:
  app:
    image: node:20.11.1-slim
    container_name: crococroc-nuxt3
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NUXT_HOST=0.0.0.0
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_ORIGIN=${AUTH_ORIGIN}
      - NUXT_SESSION_PASSWORD=${NUXT_SESSION_PASSWORD}
    volumes:
      - crococroc_data:/app
    working_dir: /app
    command: sh -c "corepack enable && pnpm install && pnpm run build && node .output/server/index.mjs"
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d:ro
      - certbot_conf:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot:ro
    depends_on:
      - app
    networks:
      - web

volumes:
  crococroc_data:
  nginx_conf:
  certbot_conf:
  certbot_www:

networks:
  web:
    name: crococroc_network
    driver: bridge