@"
version: '3'

services:
  app:
    build: .
    container_name: crococroc-nuxt3
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NUXT_HOST=0.0.0.0
      - DATABASE_URL=\${DATABASE_URL}
      - AUTH_SECRET=\${AUTH_SECRET}
      - AUTH_ORIGIN=\${AUTH_ORIGIN}
      - NUXT_SESSION_PASSWORD=\${NUXT_SESSION_PASSWORD}
    depends_on:
      - db
    networks:
      - web

  db:
    image: postgres:15-alpine
    container_name: crococroc-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=Sonceboz2025+
      - POSTGRES_DB=crococroc
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - web

volumes:
  postgres_data:

networks:
  web:
    driver: bridge
"@ | Out-File -FilePath docker-compose.yml -Encoding utf8